name: SonarCloud

on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  sonarcloud:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarCloud Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-macosx.zip
          unzip sonar-scanner.zip -d ~/sonar-scanner
          export PATH="~/sonar-scanner/sonar-scanner-4.6.2.2472-macosx/bin:$PATH"

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ~/sonar-scanner/sonar-scanner-4.6.2.2472-macosx/bin/sonar-scanner \
          -Dsonar.organization=priscigs \
          -Dsonar.projectKey=Priscigs_sonarcloud-analysis \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io
